services:
  web:
    image: node:22.12.0
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "127.0.0.1:5173:5173"
    command: sh -c "npm install && npm run dev"
    env_file:
      - ./.env